-- <autogenerated>
--   This file is generated from T4 template dbo.Products_Update.proc.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

create procedure [dbo].[Products_Update]
    @ProductID int,
    @ProductName nvarchar(40),
    @SupplierID int,
    @CategoryID int,
    @QuantityPerUnit nvarchar(20),
    @UnitPrice money,
    @UnitsInStock smallint,
    @UnitsOnOrder smallint,
    @ReorderLevel smallint,
    @Discontinued bit,
    @TimeStamp timestamp output 
as
begin
	update [dbo].[Products] 
	set
		[ProductName] = @ProductName,
        [SupplierID] = @SupplierID,
        [CategoryID] = @CategoryID,
        [QuantityPerUnit] = @QuantityPerUnit,
        [UnitPrice] = @UnitPrice,
        [UnitsInStock] = @UnitsInStock,
        [UnitsOnOrder] = @UnitsOnOrder,
        [ReorderLevel] = @ReorderLevel,
        [Discontinued] = @Discontinued	
	where
		[ProductID] = @ProductID and
        [TimeStamp] = @TimeStamp	

	set nocount on
    
	-- Return TimeStamp value generated by SQL Server
	select @TimeStamp = [TimeStamp] from [Products] where [ProductID] = @ProductID
end

