-- <autogenerated>
--   This file is generated from T4 template dbo.Products_Insert.proc.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

create procedure [dbo].[Products_Insert]
    @ProductName nvarchar(40),
    @SupplierID int,
    @CategoryID int,
    @QuantityPerUnit nvarchar(20),
    @UnitPrice money,
    @UnitsInStock smallint,
    @UnitsOnOrder smallint,
    @ReorderLevel smallint,
    @Discontinued bit,
    @ProductID int output,
    @TimeStamp timestamp output 
as
begin
	insert into [dbo].[Products] 
	(
		[ProductName],
        [SupplierID],
        [CategoryID],
        [QuantityPerUnit],
        [UnitPrice],
        [UnitsInStock],
        [UnitsOnOrder],
        [ReorderLevel],
        [Discontinued]	
    ) 
    values 
    (
		@ProductName,
        @SupplierID,
        @CategoryID,
        @QuantityPerUnit,
        @UnitPrice,
        @UnitsInStock,
        @UnitsOnOrder,
        @ReorderLevel,
        @Discontinued 
    )
    
    set nocount on
    
	-- Return ProductID value of the new row
	set @ProductID = scope_identity()

	-- Return TimeStamp value generated by SQL Server
	select @TimeStamp = [TimeStamp] from [Products] where [ProductID] = @ProductID
end

