-- <autogenerated>
--   This file is generated from T4 template dbo.Products_Delete.proc.tt. 
--   Any changes made manually will be lost next time this file is regenerated.
-- </autogenerated>

create procedure [dbo].[Products_Delete]
    @ProductID int,
    @TimeStamp timestamp 
as
begin
	delete from [dbo].[Products] 
	where
		[ProductID] = @ProductID and
        [TimeStamp] = @TimeStamp	
end

